# Generated by Django 4.0.4 on 2022-05-05 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0002_alter_receipt_account_alter_receipt_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='receipts.account'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='receipts.category'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='tax',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='total',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='vendor',
            field=models.CharField(max_length=200),
        ),
    ]
