# Generated by Django 4.0.4 on 2022-05-05 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0003_alter_receipt_account_alter_receipt_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipt',
            old_name='owner',
            new_name='purchaser',
        ),
    ]
